name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: net9.0
          - os: macos-latest
            target: net9.0
          - os: windows-latest
            target: net9.0-android
          - os: macos-latest
            target: net9.0-ios

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Install required workloads
      run: |
        dotnet workload install maui

    - name: Install Android SDK (for Android builds)
      if: ${{ matrix.target == 'net9.0-android' }}
      run: |
        echo "y" | sdkmanager "platforms;android-35" "build-tools;35.0.0" "system-images;android-35;google_apis;x86_64"

    - name: Install Xcode (for iOS builds)
      if: ${{ matrix.os == 'macos-latest' && matrix.target == 'net9.0-ios' }}
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Build
      run: dotnet build -c Release -f ${{ matrix.target }} -o build-${{ matrix.target }}

    - name: Zip build folder
      run: zip -r build-${{ matrix.target }}.zip build-${{ matrix.target }}
    
    - name: Create Github Release
      uses: softprops/action-gh-release@v2.1.0
      with:
        tag_name: testing-phase
        name: 'Testing Phase Release'
        files: build-${{ matrix.target }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    